PREFIX fse:   <http://opencaesar.io/examples/firesat/disciplines/fse/fse#>
PREFIX base:   <http://imce.jpl.nasa.gov/foundation/base#>
PREFIX mission:   <http://imce.jpl.nasa.gov/foundation/mission#>
PREFIX space:   <http://opencaesar.io/examples/firesat_fun/vocabularies/space#>


SELECT DISTINCT ?m ?m_ownsDataFlow

WHERE {
	?m a space:Function ;
		space:ownsDataFlow ?m_ownsDataFlow
}
ORDER BY ?m ?m_ownsDataFlow

