PREFIX fse:   <http://opencaesar.io/examples/firesat/disciplines/fse/fse#>
PREFIX base:   <http://imce.jpl.nasa.gov/foundation/base#>
PREFIX mission:   <http://imce.jpl.nasa.gov/foundation/mission#>
PREFIX space:   <http://opencaesar.io/examples/firesat_fun/vocabularies/space#>


SELECT DISTINCT ?invoking_function ?invoked_function ?performer ?ownedConnector ?activity_input_pin ?activity_output_pin ?function_input_pin ?function_output_pin

WHERE {
	?invoking_function a space:Function ;
		mission:invokes ?invoked_function ;
		space:ownsConnector ?ownedConnector ;
		space:hasInput ?activity_input_pin ;
		space:hasOutput ?activity_output_pin .
	?invoked_function mission:isPerformedBy ?performer .
	?invoked_function space:hasInput ?function_input_pin ;
		space:hasOutput ?function_output_pin .
	
}
ORDER BY ?invoking_function ?invoked_function ?performer ?activity_input_pin ?activity_output_pin ?function_input_pin ?function_output_pin


