PREFIX fse:   <http://opencaesar.io/examples/firesat/disciplines/fse/fse#>
PREFIX base:   <http://imce.jpl.nasa.gov/foundation/base#>
PREFIX mission:   <http://imce.jpl.nasa.gov/foundation/mission#>
PREFIX space:   <http://opencaesar.io/examples/firesat_fun/vocabularies/space#>


SELECT DISTINCT ?m  ?m_contains

WHERE {
	?m a space:Spacecraft ;
		base:contains ?m_contains ;
		
}
ORDER BY ?m  ?m_contains

